version: '3.9'
services:
  redis:
    image:  redis
    container_name: redis
    ports:  
     - 6379:6379
    volumes:
     - ./data/redis:/data
     - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf


  mysql:
    image: mysql
    container_name: mysql_ktb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=go_ktb_test
    ports:
     - 3306:3306
    volumes:
     - ./data/mysql:/var/lib/mysql

